<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Appointment Report</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
            line-height: 1.5;
        }
        h1 {
            text-align: center;
            font-size: 24px;
            margin-bottom: 10px;
        }
        h2 {
            text-align: center;
            font-size: 20px;
            margin-bottom: 5px;
        }
        .header, .footer {
            text-align: center;
            margin-bottom: 20px;
        }
        .clinic-details {
            margin-bottom: 30px;
        }
        .clinic-details p {
            margin: 0;
        }
        .appointment-info {
            margin-bottom: 20px;
        }
        .appointment-info p {
            margin: 5px 0;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin: 20px 0;
        }
        th, td {
            border: 1px solid #ddd;
            padding: 10px;
            text-align: left;
        }
        th {
            background-color: #f2f2f2;
        }
        .footer {
            margin-top: 30px;
            font-size: 0.8em;
        }
    </style>
</head>
<body>

<div class="header">
    <img src="img/logokliniksafamedic" alt="">
    <h1>Clinic Appointment Report</h1>
    <h2>Safamedic Clinic</h2>
    <p>Date: {{ date('Y-m-d') }}</p>
</div>

<div class="clinic-details">
    <p><strong>Address:</strong> Hulu Langat, Malaysia</p>
    <p><strong>Phone:</strong> 016-902 2505</p>
    <p><strong>Email:</strong> Kliniksafamedichululangat@gmail.com</p>
</div>

<div class="appointment-info">
    <p><strong>Patient Name:</strong> {{ $appointment->patientName }}</p>
    <p><strong>Doctor Name:</strong> {{ $appointment->doctorName }}</p>
    <p><strong>Appointment Date:</strong> {{ $appointment->appointmentDate }}</p>
    <p><strong>Appointment Time:</strong> {{ $appointment->appointmentTime }}</p>
    <p><strong>Reason for Visit:</strong> {{ $appointment->reason }}</p>
    <p><strong>Service Name:</strong> {{ $appointment->serviceName }}</p>
</div>

<div class="footer">
    <p>Generated by: Clinic Appointment System</p>
    <p>Contact: abshardanial36@gmail.com</p>
</div>

</body>
</html>
